# Generated by Django 2.0 on 2018-01-10 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDateTime', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('state', models.IntegerField(choices=[(0, '同意'), (1, '不同意'), (2, '待定')], default=0, verbose_name='意愿')),
                ('remark', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('age', models.IntegerField(default=0)),
                ('educationBackgroud', models.IntegerField(choices=[(0, '大专以下'), (1, '大专'), (2, '本科')], default=0, verbose_name='学历')),
                ('sex', models.IntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别')),
            ],
        ),
        migrations.AddField(
            model_name='callhistory',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twentyFour.Resume'),
        ),
    ]
