# Generated by Django 2.0 on 2018-01-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twentyFour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callhistory',
            name='state',
            field=models.IntegerField(choices=[(0, '同意'), (1, '不同意'), (2, '待定')], default=2, verbose_name='意愿'),
        ),
    ]
