# Generated by Django 2.0 on 2018-01-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twentyFour', '0002_auto_20180111_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='states',
            field=models.IntegerField(choices=[(0, '离职'), (1, '在公司入职'), (2, '在其他公司入职')], default=0, verbose_name='状态'),
        ),
    ]
