# Generated by Django 2.0 on 2018-01-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twentyFour', '0003_resume_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callhistory',
            name='state',
            field=models.IntegerField(choices=[(0, '同意'), (1, '待定'), (2, '不同意')], default=2, verbose_name='意愿'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='states',
            field=models.IntegerField(choices=[(0, '离职'), (1, '入职'), (2, '拒绝')], default=0, verbose_name='状态'),
        ),
    ]
