# Generated by Django 2.0 on 2018-01-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twentyFour', '0004_auto_20180111_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='states',
            field=models.BooleanField(default=True, verbose_name='能否拨打'),
        ),
    ]
