# Generated by Django 2.0 on 2018-01-11 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('twentyFour', '0005_auto_20180111_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='createDateTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建日期'),
            preserve_default=False,
        ),
    ]
